### ISSUE TITLE
Editor's test window is inconsistent with what actually happens.

### ISSUE THREAD

**Issue by edderiofer** [increpare/PuzzleScript#484] opened 2018-08-05 14:12 UTC
In [this project](https://www.puzzlescript.net/play.html?p=3a7d1951661b29327b0e4d2dd6c7eed3), pressing X then up has a different behaviour depending on whether you're in the editor or if you're on the game page.

**Comment by increpare** [comment] 2018-08-05 23:26
oh geeze it sure does. thanks for letting me know.  if you could make an
even simpler example reproduction example that would help, otherwise, I'll
try to get around to it sooner rather than later.

(i hope this isn't blocking you right now? if so let me know and I'll push
it up to tip-top priority)

2018-08-05 16:12 GMT+02:00 edderiofer <notifications@github.com>:

**Comment by increpare** [comment] 2018-08-05 23:29
OH, spooky, I think i know what the problem is.  If in the editor after
moving, you resize the browser window, does the display update and correct
itself? it looks like it might be forgetting to redraw itself for some
reason

2018-08-06 1:26 GMT+02:00 Stephen Lavelle <analytic@gmail.com>:

**Comment by increpare** [comment] 2018-08-05 23:30
question 2: does commenting out "verbose_logging" fix the behaviour for you?

2018-08-06 1:29 GMT+02:00 Stephen Lavelle <analytic@gmail.com>:

**Comment by edderiofer** [comment] 2018-08-06 23:42
Yes on both counts.

**Comment by increpare** [comment] 2021-02-08 17:50
seems to magically work for me now. closing. (tested on chrome and firefox).

Thanks again for the report!

**Closed by increpare** 2021-02-08 17:50 UTC
