### ISSUE TITLE
This test should pass but it fails because it does not record all inputs

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#983] opened 2023-12-15 02:15 UTC
Here is the test case:
```
	[
		"Autowin",
		["title Autowin\nauthor lazugod\n\nnoaction\nrequire_player_movement\n\n========\nOBJECTS\n========\n\nBackground .\nblack\n\nPlayer p\nwhite\n.....\n.000.\n.000.\n00000\n.0.0.\n\nCrate c\norange\n00000\n0...0\n0...0\n0...0\n00000\n\nWall #\nbrown\n\n=======\nLEGEND\n=======\n\n=======\nSOUNDS\n=======\n\n================\nCOLLISIONLAYERS\n================\n\nBackground\nPlayer, Crate, Wall\n\n======\nRULES\n====== \n\n[ > Player | Crate ] -> [ > Player | > Crate ]\n[ > Player | Crate | no Crate no Wall ] -> Cancel Message Canceled push message\n\n==============\nWINCONDITIONS\n==============\n\nno Player\nno Wall\nno Crate\n\n=======\nLEVELS\n=======\n\n#####\n#.cp#\n#####\n\nMessage Should-be-unreachable victory\n",[1,1],"background wall:0,0,0,0,background:1,\n0,0,background crate:2,0,0,\nbackground player:3,0,0,0,0,\n","1","1702602792273.4832",[]]
	],
```
The actual input was "left,X,left,X" but "[1,1]" shows that only the arrow keys were recorded.

**Comment by david-pfx** [comment] 2024-02-20 23:55
The program:
[lazugod_autowin.txt](https://github.com/increpare/PuzzleScript/files/14352294/lazugod_autowin.txt)

The input: left,X,left,X

The output:
[
"Autowin",
["title Autowin\nauthor lazugod\n\nnoaction\nrequire_player_movement\n\n========\nOBJECTS\n========\n\nBackground .\nblack\n\nPlayer p\nwhite\n.....\n.000.\n.000.\n00000\n.0.0.\n\nCrate c\norange\n00000\n0...0\n0...0\n0...0\n00000\n\nWall #\nbrown\n\n=======\nLEGEND\n=======\n\n=======\nSOUNDS\n=======\n\n================\nCOLLISIONLAYERS\n================\n\nBackground\nPlayer, Crate, Wall\n\n======\nRULES\n====== \n\n[ > Player | Crate ] -> [ > Player | > Crate ]\n[ > Player | Crate | no Crate no Wall ] -> Cancel Message Canceled push message\n\n==============\nWINCONDITIONS\n==============\n\nno Player\nno Wall\nno Crate\n\n=======\nLEVELS\n=======\n\n#####\n#.cp#\n#####\n\nMessage Should-be-unreachable victory\n",[1,1],"background wall:0,0,0,0,background:1,\n0,0,background crate:2,0,0,\nbackground player:3,0,0,0,0,\n",0,"1708473053336.5632",[]]
],

**Comment by increpare** [comment] 2024-02-21 00:24
that test passes though (the level index (before '1708473053336.5632 ') is 0 rather than 1.  🤔

**Comment by david-pfx** [comment] 2024-02-21 00:55
This issue was raised a couple of months back, and I forget the detail. The intended point was that the test capture and runner do not correctly test the behaviour of games that rely on text screens, because they don't capture and record and replay non-game inputs.

I guess you close this one and I'll try to come up with a more compelling example.

**Comment by increpare** [comment] 2024-02-21 08:23
So, thanking you for your efforts, I'm going to sum up:

You gave me a test case that crashed, and I can confirm that it crashes, but that's because the test case looks invalid because of the level index being wrong.  I cannot reproduce this test case

The stuff about test action keys not being recorded during messages, isn't material to the broken test provided.

Closing as could not reproduce.

**Closed by increpare** 2024-02-21 08:23 UTC
