### ISSUE TITLE
Suggested new commands

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#423] opened 2018-01-25 01:31 UTC
New action commands:
Undo -- to do the same as Z
Back, to repeat an earlier level
Skip, to move to the next level (if enabled)
Also:
Auto-save and restore progress (current level)

**Comment by ncrecc** [comment] 2018-02-12 00:06
I believe there was some debate about undo and the auto-save thing (setting and resetting states) as commands, either here or on the PuzzleScript Google Groups, and the answer was that it would make PS too complicated. I'd love to see it, though, if inc ever changes his mind.

**Comment by increpare** [comment] 2018-02-12 10:13
skip - already exists - you can trigger 'win' as a command whenevery ou want
"Auto-save and restore progress (current level)" - there's already a checkpoint command that does this?  or, do you want it to happen every turn? i guess you could call it every turn.

( cf https://www.puzzlescript.net/Documentation/rules.html )

**Comment by increpare** [comment] 2018-02-12 10:14
(not interested in keeping this open.  IIRC it's a duplicate of other things that you can find if you look)

**Closed by increpare** 2018-02-12 10:14 UTC

**Comment by david-pfx** [comment] 2018-02-13 00:44
I would like a user to be able to 

(a)    stop any time and resume later, either at precisely the point of stopping or at the last checkpoint/level

(b)   selectively play or replay a specific level, either by selecting from a menu or by entering the name of a level.

 

I would see those as options to be enabled/disabled by the designer. From personal experience, I often cannot complete all the levels in a single session and I often want to replay a level immediately after completing it to see if I can do better. PuzzleScript frustrates that.

 

Here is an example: http://www.draknek.org/games/puzzlescript/hack-the-net.php (looks like a PuzzleScript fork).

 

Regards

David M Bennett FACS

  _____  

Polygamo – A Language Compiler and General Player for Abstract Games and Puzzles -- http://www.polyomino.com <http://www.polyomino.com/>
